spring:
  application:
    name: temperature-microservice
  datasource:
    url: "jdbc:h2:mem:tempdb"
    username: sa
    password: password

server:
  port: 8090

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://host.docker.internal:8761/eureka/"
      #defaultZone: "http://localhost:8761/eureka/"